version: "3"
# There is an error somewhere, double check it later, possibly in the port mapping
services:
  timeoff-mysqldb:
    image: mysql:5.7
    container_name: "timeoff-mysqldb"
    networks:
      - timeoff-mysql
    ports:
      - 3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=time_off_management
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-pWp770521", "--silent"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s

  time-off-app:
    build: .
    container_name: "time-off-app"
    restart: always
    ports:
      - 8080:8080
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://timeoff-mysqldb:3306/time_off_management?useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
     - DATABASE_HOST=timeoff-mysqldb
     - DATABASE_NAME=time_off_management
     - DATABASE_PORT=3306
     - WAIT_HOSTS=timeoff-mysqldb:3306
     - WAIT_HOSTS_TIMEOUT=300
     - WAIT_SLEEP_INTERVAL=30
     - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
     - timeoff-mysql 
    depends_on:
       timeoff-mysqldb:
          condition: service_healthy




networks:
  timeoff-mysql: